import award from "../assets/award.png";
import suitecase from "../assets/suitecase.png";
import notes from "../assets/notes.png"

export const smallSideCardData = [
  {
    heading: 'Import a certificate',
    description: 'Showing a credential may increase your chances of earning by 4 times.',
    logo: award
  },
  {
    heading: 'My jobs',
    description: 'View your active contracts, timesheets, and available earnings.',
    logo: suitecase
  },
  {
    heading: 'My purposals',
    description: 'Review your proposals, offers, referrals, and client invitations.',
    logo: notes
  }
]

export const JobsData = [
  {
    "id": 1,
    "job_title": "Web Developer",
    "job_description": "Develop a responsive website using HTML, CSS, and JavaScript.",
    "type": "Full-Time",
    "level_of_expertise": "Mid-Level",
    "budget": 5000,
    "budget_type": "Fixed Price",
    "posted_time": "2023-09-01T10:00:00Z",
    "skills_required": ["HTML", "CSS", "JavaScript"],
    "total_proposals": 10,
    "payment": 0,
    "previous_spend_money": 0,
    "ratings": 4.8,
    "project_type": "Website Development",
    "hired": false,
    "interviewing": true,
    "invites_sent": 5,
    "unanswered_invites": 2,
    "country": 'United States'
  },
  {
    "id": 2,
    "job_title": "Graphic Designer",
    "job_description": "Create visually appealing graphics and illustrations for marketing materials.",
    "type": "Part-Time",
    "level_of_expertise": "Entry-Level",
    "budget": 20,
    "budget_type": "Hourly Rate",
    "posted_time": "2023-08-28T14:30:00Z",
    "skills_required": ["Adobe Photoshop", "Illustrator"],
    "total_proposals": 15,
    "payment": 100,
    "previous_spend_money": 500,
    "ratings": 4.5,
    "project_type": "Graphic Design",
    "hired": true,
    "interviewing": false,
    "invites_sent": 3,
    "unanswered_invites": 0,
    "country": 'United Kingdom'
  },
  {
    "id": 3,
    "job_title": "Front-End Developer",
    "job_description": "Build a responsive e-commerce website using React and Redux.",
    "type": "Full-Time",
    "level_of_expertise": "Senior",
    "budget": 8000,
    "budget_type": "Fixed Price",
    "posted_time": "2023-08-15T09:30:00Z",
    "skills_required": ["React", "Redux", "HTML", "CSS", "JavaScript"],
    "total_proposals": 25,
    "payment": 0,
    "previous_spend_money": 0,
    "ratings": 4.9,
    "project_type": "E-commerce",
    "hired": false,
    "interviewing": true,
    "invites_sent": 12,
    "unanswered_invites": 3,
    "country": 'United States'
  },
  {
    "id": 4,
    "job_title": "UX/UI Designer",
    "job_description": "Create user-friendly designs for a mobile app focused on health and fitness.",
    "type": "Contract",
    "level_of_expertise": "Mid-Level",
    "budget": 4000,
    "budget_type": "Fixed Price",
    "posted_time": "2023-08-20T14:15:00Z",
    "skills_required": ["UI/UX Design", "Sketch", "InVision"],
    "total_proposals": 18,
    "payment": 0,
    "previous_spend_money": 0,
    "ratings": 4.7,
    "project_type": "Mobile App",
    "hired": false,
    "interviewing": false,
    "invites_sent": 5,
    "unanswered_invites": 0,
    "country": 'India'
  },
  {
    "id": 5,
    "job_title": "Content Writer",
    "job_description": "Write engaging blog posts on technology and innovation topics.",
    "type": "Part-Time",
    "level_of_expertise": "Entry-Level",
    "budget": 15,
    "budget_type": "Hourly Rate",
    "posted_time": "2023-08-25T17:45:00Z",
    "skills_required": ["Content Writing", "SEO"],
    "total_proposals": 10,
    "payment": 120,
    "previous_spend_money": 500,
    "ratings": 4.2,
    "project_type": "Content Creation",
    "hired": true,
    "interviewing": false,
    "invites_sent": 2,
    "unanswered_invites": 0,
    "country": 'Germany'
  },
  {
    "id": 6,
    "job_title": "Upgrade Rails Application",
    "job_description": "We are looking for an experienced Ruby on Rails developer to upgrade our existing Rails application from version '4.2.11.3' to the latest version. The project involves analyzing the current codebase, updating dependencies, and ensuring the application's compatibility with the latest Rails release. The ideal candidate should have a strong background in Rails development and a proven track record of successful upgrades. This is a critical project for us, and we are committed to ensuring a smooth transition to the latest Rails version.",
    "type": "Contract",
    "level_of_expertise": "Senior",
    "budget": 6000,
    "budget_type": "Fixed Price",
    "posted_time": "2023-08-10T11:00:00Z",
    "skills_required": ["Ruby on Rails", "Database Management", "Code Refactoring"],
    "total_proposals": 8,
    "payment": 0,
    "previous_spend_money": 0,
    "ratings": 4.9,
    "project_type": "Software Development",
    "hired": true,
    "interviewing": false,
    "invites_sent": 0,
    "unanswered_invites": 0,
    "country": 'United States'
  },
  {
    "id": 7,
    "job_title": "Mobile App Developer",
    "job_description": "We are seeking a mobile app developer to create a cross-platform mobile application for our e-commerce platform. The app should be user-friendly, fast, and responsive. Experience with Flutter or React Native is required.",
    "type": "Full-Time",
    "level_of_expertise": "Mid-Level",
    "budget": 7500,
    "budget_type": "Fixed Price",
    "posted_time": "2023-08-05T15:30:00Z",
    "skills_required": ["Flutter", "React Native", "Mobile App Development"],
    "total_proposals": 12,
    "payment": 0,
    "previous_spend_money": 0,
    "ratings": 4.7,
    "project_type": "Mobile App Development",
    "hired": false,
    "interviewing": true,
    "invites_sent": 6,
    "unanswered_invites": 1,
    "country": 'Denmark'
  },
  {
    "id": 8,
    "job_title": "Data Analyst",
    "job_description": "We need a skilled data analyst to analyze our sales data, customer behavior, and market trends. You will be responsible for generating insights and recommendations to optimize our business strategies.",
    "type": "Part-Time",
    "level_of_expertise": "Senior",
    "budget": 25,
    "budget_type": "Hourly Rate",
    "posted_time": "2023-08-12T10:15:00Z",
    "skills_required": ["Data Analysis", "Statistics", "SQL", "Data Visualization"],
    "total_proposals": 7,
    "payment": 0,
    "previous_spend_money": 0,
    "ratings": 4.8,
    "project_type": "Data Analysis",
    "hired": false,
    "interviewing": false,
    "invites_sent": 3,
    "unanswered_invites": 0,
    "country": 'United Kingdom'
  },
  {
    "id": 8,
    "job_title": "Content Marketing Manager",
    "job_description": "We are looking for an experienced content marketing manager to oversee our content strategy. You will be responsible for creating and distributing high-quality content, managing a team of writers, and driving organic traffic to our website.",
    "type": "Full-Time",
    "level_of_expertise": "Senior",
    "budget": 9000,
    "budget_type": "Fixed Price",
    "posted_time": "2023-08-20T13:00:00Z",
    "skills_required": ["Content Marketing", "SEO", "Team Management"],
    "total_proposals": 9,
    "payment": 0,
    "previous_spend_money": 0,
    "ratings": 4.9,
    "project_type": "Marketing",
    "hired": true,
    "interviewing": false,
    "invites_sent": 0,
    "unanswered_invites": 0,
    "country": 'India'
  },
  {
    "id": 9,
    "job_title": "Machine Learning Engineer",
    "job_description": "We are seeking a machine learning engineer to develop and deploy predictive models for our recommendation system. You will work with large datasets and implement cutting-edge algorithms to enhance user experience.",
    "type": "Full-Time",
    "level_of_expertise": "Senior",
    "budget": 9500,
    "budget_type": "Fixed Price",
    "posted_time": "2023-08-25T14:45:00Z",
    "skills_required": ["Machine Learning", "Python", "Deep Learning", "TensorFlow"],
    "total_proposals": 5,
    "payment": 0,
    "previous_spend_money": 0,
    "ratings": 4.9,
    "project_type": "Machine Learning",
    "hired": false,
    "interviewing": true,
    "invites_sent": 3,
    "unanswered_invites": 1,
    "country": 'Germany'
  },
  {
    "id": 10,
    "job_title": "Blockchain Developer",
    "job_description": "We are looking for a blockchain developer to work on a decentralized application (dApp) project. You will be responsible for smart contract development, token integration, and ensuring the security of the blockchain ecosystem.",
    "type": "Contract",
    "level_of_expertise": "Mid-Level",
    "budget": 5500,
    "budget_type": "Fixed Price",
    "posted_time": "2023-08-18T12:30:00Z",
    "skills_required": ["Blockchain", "Solidity", "Smart Contracts", "Ethereum"],
    "total_proposals": 10,
    "payment": 0,
    "previous_spend_money": 0,
    "ratings": 4.8,
    "project_type": "Blockchain Development",
    "hired": false,
    "interviewing": false,
    "invites_sent": 4,
    "unanswered_invites": 0,
    "country": 'United States'
  },
  {
    "id": 11,
    "job_title": "Cybersecurity Analyst",
    "job_description": "Join our cybersecurity team and protect our organization's digital assets from cyber threats. You will monitor network activity, conduct vulnerability assessments, and implement security measures to safeguard our data.",
    "type": "Full-Time",
    "level_of_expertise": "Mid-Level",
    "budget": 8200,
    "budget_type": "Fixed Price",
    "posted_time": "2023-08-22T16:15:00Z",
    "skills_required": ["Cybersecurity", "Network Monitoring", "Vulnerability Assessment", "Incident Response"],
    "total_proposals": 8,
    "payment": 0,
    "previous_spend_money": 0,
    "ratings": 4.7,
    "project_type": "Cybersecurity",
    "hired": false,
    "interviewing": false,
    "invites_sent": 2,
    "unanswered_invites": 0,
    "country": 'Dubai'
  },
  {
    "id": 12,
    "job_title": "AI Research Scientist",
    "job_description": "Join our AI research team to work on cutting-edge projects in natural language processing, computer vision, and reinforcement learning. You will be responsible for developing and experimenting with AI algorithms and models to advance our AI capabilities.",
    "type": "Full-Time",
    "level_of_expertise": "Senior",
    "budget": 11000,
    "budget_type": "Fixed Price",
    "posted_time": "2023-08-30T09:00:00Z",
    "skills_required": ["Artificial Intelligence", "Machine Learning", "Python", "Deep Learning"],
    "total_proposals": 6,
    "payment": 0,
    "previous_spend_money": 0,
    "ratings": 4.9,
    "project_type": "AI Research",
    "hired": false,
    "interviewing": true,
    "invites_sent": 2,
    "unanswered_invites": 0,
    "country": 'Dubai'
  },
  {
    "id": 13,
    "job_title": "AI Chatbot Developer",
    "job_description": "We are looking for an AI chatbot developer to create a conversational AI system that enhances customer support and engagement. You will design and implement chatbots that understand and respond to user queries effectively.",
    "type": "Contract",
    "level_of_expertise": "Mid-Level",
    "budget": 6000,
    "budget_type": "Fixed Price",
    "posted_time": "2023-08-25T14:30:00Z",
    "skills_required": ["Natural Language Processing", "Chatbot Development", "Python"],
    "total_proposals": 9,
    "payment": 0,
    "previous_spend_money": 0,
    "ratings": 4.8,
    "project_type": "AI Chatbots",
    "hired": true,
    "interviewing": false,
    "invites_sent": 0,
    "unanswered_invites": 0,
    "country": 'United States'
  },
  {
    "id": 14,
    "job_title": "Computer Vision Engineer",
    "job_description": "Join our computer vision team to work on projects related to image and video analysis. You will develop algorithms for object recognition, image segmentation, and video tracking, contributing to our AI-powered applications.",
    "type": "Full-Time",
    "level_of_expertise": "Mid-Level",
    "budget": 9500,
    "budget_type": "Fixed Price",
    "posted_time": "2023-08-20T11:45:00Z",
    "skills_required": ["Computer Vision", "OpenCV", "Python", "Deep Learning"],
    "total_proposals": 7,
    "payment": 0,
    "previous_spend_money": 0,
    "ratings": 4.7,
    "project_type": "Computer Vision",
    "hired": false,
    "interviewing": true,
    "invites_sent": 3,
    "unanswered_invites": 1,
    "country": 'India'
  },
  {
    "id": 15,
    "job_title": "DevOps Engineer",
    "job_description": "We are seeking a skilled DevOps engineer to streamline our software development and deployment processes. You will be responsible for automating CI/CD pipelines, managing infrastructure as code, and ensuring high availability and reliability of our applications.",
    "type": "Full-Time",
    "level_of_expertise": "Mid-Level",
    "budget": 8500,
    "budget_type": "Fixed Price",
    "posted_time": "2023-08-28T10:00:00Z",
    "skills_required": ["DevOps", "CI/CD", "Docker", "Kubernetes"],
    "total_proposals": 10,
    "payment": 0,
    "previous_spend_money": 0,
    "ratings": 4.8,
    "project_type": "DevOps",
    "hired": false,
    "interviewing": true,
    "invites_sent": 5,
    "unanswered_invites": 2,
    "country": 'Finland'
  },
  {
    "id": 16,
    "job_title": "Cloud Solutions Architect",
    "job_description": "Join our team as a Cloud Solutions Architect to design and implement cloud-based solutions using AWS, Azure, or Google Cloud Platform. You will collaborate with development teams to optimize cloud infrastructure and ensure scalability.",
    "type": "Full-Time",
    "level_of_expertise": "Senior",
    "budget": 11000,
    "budget_type": "Fixed Price",
    "posted_time": "2023-08-15T14:30:00Z",
    "skills_required": ["Cloud Architecture", "AWS", "Azure", "Google Cloud"],
    "total_proposals": 8,
    "payment": 0,
    "previous_spend_money": 0,
    "ratings": 4.9,
    "project_type": "Cloud Solutions",
    "hired": false,
    "interviewing": false,
    "invites_sent": 3,
    "unanswered_invites": 0,
    "country": 'United States'
  },
  {
    "id": 17,
    "job_title": "Site Reliability Engineer (SRE)",
    "job_description": "We are looking for a Site Reliability Engineer (SRE) to ensure the reliability, availability, and performance of our services. You will monitor systems, troubleshoot incidents, and work on automation and scalability projects.",
    "type": "Full-Time",
    "level_of_expertise": "Mid-Level",
    "budget": 9000,
    "budget_type": "Fixed Price",
    "posted_time": "2023-08-22T11:15:00Z",
    "skills_required": ["Site Reliability Engineering", "Monitoring", "Automation", "Scalability"],
    "total_proposals": 6,
    "payment": 0,
    "previous_spend_money": 0,
    "ratings": 4.7,
    "project_type": "SRE",
    "hired": true,
    "interviewing": false,
    "invites_sent": 0,
    "unanswered_invites": 0,
    "country": 'United Kingdom'
  },
  {
    "id": 18,
    "job_title": "Video Editor",
    "job_description": "We are looking for a skilled video editor to join our team and produce high-quality video content. You will be responsible for editing raw footage, adding special effects, and ensuring the final product meets our creative vision.",
    "type": "Part-Time",
    "level_of_expertise": "Mid-Level",
    "budget": 30,
    "budget_type": "Hourly Rate",
    "posted_time": "2023-08-20T09:30:00Z",
    "skills_required": ["Video Editing", "Adobe Premiere Pro", "After Effects", "Color Correction"],
    "total_proposals": 12,
    "payment": 0,
    "previous_spend_money": 0,
    "ratings": 4.8,
    "project_type": "Video Editing",
    "hired": false,
    "interviewing": true,
    "invites_sent": 6,
    "unanswered_invites": 2,
    "country": 'Brazil'
  },
  {
    "id": 19,
    "job_title": "Videographer",
    "job_description": "Join our team as a videographer to capture stunning footage and create engaging video content. You will be responsible for planning shoots, operating camera equipment, and collaborating with the creative team.",
    "type": "Full-Time",
    "level_of_expertise": "Mid-Level",
    "budget": 7500,
    "budget_type": "Fixed Price",
    "posted_time": "2023-08-18T14:15:00Z",
    "skills_required": ["Videography", "Camera Operation", "Storyboarding", "Video Production"],
    "total_proposals": 8,
    "payment": 0,
    "previous_spend_money": 0,
    "ratings": 4.7,
    "project_type": "Videography",
    "hired": false,
    "interviewing": false,
    "invites_sent": 4,
    "unanswered_invites": 0,
    "country": 'Russia'
  },
  {
    "id": 20,
    "job_title": "Video Production Manager",
    "job_description": "We are seeking a video production manager to oversee our video content creation process. You will manage the production team, coordinate shoots, and ensure the timely delivery of high-quality videos.",
    "type": "Full-Time",
    "level_of_expertise": "Senior",
    "budget": 9500,
    "budget_type": "Fixed Price",
    "posted_time": "2023-08-25T16:00:00Z",
    "skills_required": ["Video Production", "Project Management", "Team Leadership"],
    "total_proposals": 6,
    "payment": 0,
    "previous_spend_money": 0,
    "ratings": 4.9,
    "project_type": "Video Production",
    "hired": true,
    "interviewing": false,
    "invites_sent": 0,
    "unanswered_invites": 0,
    "country": 'Russia'
  },
  {
    "id": 21,
    "job_title": "Cybersecurity Analyst",
    "job_description": "We are looking for a skilled cybersecurity analyst to protect our organization from cyber threats. You will analyze security vulnerabilities, monitor network traffic, and implement security measures to safeguard our data.",
    "type": "Full-Time",
    "level_of_expertise": "Mid-Level",
    "budget": 8500,
    "budget_type": "Fixed Price",
    "posted_time": "2023-08-28T10:30:00Z",
    "skills_required": ["Cybersecurity", "Vulnerability Assessment", "Network Security", "Incident Response"],
    "total_proposals": 9,
    "payment": 0,
    "previous_spend_money": 0,
    "ratings": 4.7,
    "project_type": "Cybersecurity",
    "hired": false,
    "interviewing": true,
    "invites_sent": 4,
    "unanswered_invites": 1,
    "country": 'India'
  },
  {
    "id": 22,
    "job_title": "Machine Learning Engineer",
    "job_description": "Join our machine learning team to develop and deploy advanced AI models. You will work on natural language processing, computer vision, and recommendation systems, contributing to our AI-powered products.",
    "type": "Full-Time",
    "level_of_expertise": "Senior",
    "budget": 11000,
    "budget_type": "Fixed Price",
    "posted_time": "2023-08-15T14:45:00Z",
    "skills_required": ["Machine Learning", "Deep Learning", "Python", "TensorFlow"],
    "total_proposals": 11,
    "payment": 0,
    "previous_spend_money": 0,
    "ratings": 4.9,
    "project_type": "Machine Learning",
    "hired": false,
    "interviewing": true,
    "invites_sent": 3,
    "unanswered_invites": 0,
    "country": 'Brazil'
  },
  {
    "id": 23,
    "job_title": "DevOps Engineer",
    "job_description": "We are seeking a DevOps engineer to improve our software development and deployment processes. You will automate CI/CD pipelines, manage infrastructure as code, and ensure the reliability of our applications.",
    "type": "Full-Time",
    "level_of_expertise": "Mid-Level",
    "budget": 9000,
    "budget_type": "Fixed Price",
    "posted_time": "2023-08-20T11:00:00Z",
    "skills_required": ["DevOps", "CI/CD", "Docker", "Kubernetes"],
    "total_proposals": 8,
    "payment": 0,
    "previous_spend_money": 0,
    "ratings": 4.8,
    "project_type": "DevOps",
    "hired": true,
    "interviewing": false,
    "invites_sent": 0,
    "unanswered_invites": 0,
    "country": 'France'
  },
  {
    "id": 24,
    "job_title": "YouTube Content Creator",
    "job_description": "We are looking for a creative YouTube content creator to produce engaging video content for our YouTube channel. You will be responsible for planning, filming, editing, and publishing videos that resonate with our target audience.",
    "type": "Part-Time",
    "level_of_expertise": "Entry-Level",
    "budget": 35,
    "budget_type": "Per Video",
    "posted_time": "2023-08-10T13:30:00Z",
    "skills_required": ["Video Editing", "Content Creation", "YouTube SEO", "Camera Operation"],
    "total_proposals": 14,
    "payment": 0,
    "previous_spend_money": 0,
    "ratings": 4.5,
    "project_type": "YouTube Content",
    "hired": false,
    "interviewing": true,
    "invites_sent": 5,
    "unanswered_invites": 2,
    "country": 'China'
  },
  {
    "id": 25,
    "job_title": "YouTube Marketing Specialist",
    "job_description": "Join our team as a YouTube marketing specialist to grow our YouTube channel's audience and engagement. You will develop and execute YouTube marketing strategies, optimize video metadata, and analyze performance metrics.",
    "type": "Full-Time",
    "level_of_expertise": "Mid-Level",
    "budget": 9000,
    "budget_type": "Fixed Price",
    "posted_time": "2023-08-15T11:45:00Z",
    "skills_required": ["YouTube Marketing", "SEO", "Analytics", "Audience Growth"],
    "total_proposals": 8,
    "payment": 0,
    "previous_spend_money": 0,
    "ratings": 4.7,
    "project_type": "YouTube Marketing",
    "hired": false,
    "interviewing": false,
    "invites_sent": 3,
    "unanswered_invites": 0,
    "country": 'Canada'
  },
  {
    "id": 26,
    "job_title": "Video Thumbnail Designer",
    "job_description": "We are in search of a skilled video thumbnail designer to create eye-catching and click-worthy thumbnails for our YouTube videos. Your designs will play a crucial role in increasing our video click-through rate (CTR).",
    "type": "Part-Time",
    "level_of_expertise": "Mid-Level",
    "budget": 25,
    "budget_type": "Per Thumbnail",
    "posted_time": "2023-08-22T14:15:00Z",
    "skills_required": ["Graphic Design", "Adobe Photoshop", "YouTube Thumbnail Design"],
    "total_proposals": 6,
    "payment": 0,
    "previous_spend_money": 0,
    "ratings": 4.8,
    "project_type": "Thumbnail Design",
    "hired": true,
    "interviewing": false,
    "invites_sent": 0,
    "unanswered_invites": 0,
    "country": 'Germany'
  },
  {
    "id": 27,
    "job_title": "Digital Marketing Specialist",
    "job_description": "We are seeking a digital marketing specialist to develop and execute online marketing campaigns. You will be responsible for creating and optimizing ads, managing social media, and analyzing performance metrics.",
    "type": "Full-Time",
    "level_of_expertise": "Mid-Level",
    "budget": 8000,
    "budget_type": "Fixed Price",
    "posted_time": "2023-08-10T14:00:00Z",
    "skills_required": ["Digital Marketing", "Social Media Advertising", "Google Ads", "Analytics"],
    "total_proposals": 12,
    "payment": 0,
    "previous_spend_money": 0,
    "ratings": 4.8,
    "project_type": "Digital Marketing",
    "hired": false,
    "interviewing": true,
    "invites_sent": 5,
    "unanswered_invites": 2,
    "country": 'Canada'
  },
  {
    "id": 28,
    "job_title": "Content Marketing Manager",
    "job_description": "Join our team as a content marketing manager to lead our content strategy. You will create and distribute high-quality content, manage a team of writers, and drive organic traffic to our website.",
    "type": "Full-Time",
    "level_of_expertise": "Senior",
    "budget": 9500,
    "budget_type": "Fixed Price",
    "posted_time": "2023-08-18T10:30:00Z",
    "skills_required": ["Content Marketing", "SEO", "Team Management"],
    "total_proposals": 9,
    "payment": 0,
    "previous_spend_money": 0,
    "ratings": 4.9,
    "project_type": "Content Marketing",
    "hired": true,
    "interviewing": false,
    "invites_sent": 0,
    "unanswered_invites": 0,
    "country": 'Italy'
  },
  {
    "id": 29,
    "job_title": "Email Marketing Specialist",
    "job_description": "We are looking for an email marketing specialist to manage our email campaigns and customer communication. You will design and execute email marketing strategies to engage and retain our subscribers.",
    "type": "Part-Time",
    "level_of_expertise": "Mid-Level",
    "budget": 30,
    "budget_type": "Hourly Rate",
    "posted_time": "2023-08-25T15:15:00Z",
    "skills_required": ["Email Marketing", "Campaign Management", "Email Automation", "A/B Testing"],
    "total_proposals": 8,
    "payment": 0,
    "previous_spend_money": 0,
    "ratings": 4.7,
    "project_type": "Email Marketing",
    "hired": false,
    "interviewing": false,
    "invites_sent": 3,
    "unanswered_invites": 0,
    "country": 'United States'
  }
]